FROM golang:1.21-alpine as builder

ARG VERSION=main

# Force Go to use the cgo based DNS resolver. This is required to ensure DNS
# queries required to connect to linked containers succeed.
ENV GODEBUG netdns=cgo

# Install dependencies and install/build lnd.
RUN apk add --no-cache --update alpine-sdk \
    git \
    make 

# Copy in the local repository to build from.
RUN git clone --quiet --depth 1 --single-branch \
    --branch $VERSION \
    https://github.com/YusukeShimizu/peerswap-web /go/src/github.com/YusukeShimizu/peerswap-web

WORKDIR /go/src/github.com/YusukeShimizu/peerswap-web

# Add bash.
RUN apk add --no-cache \
    bash
RUN go mod tidy

WORKDIR /go/src/github.com/YusukeShimizu/peerswap-web/cmd/web

ENTRYPOINT ["go", "run", "main.go"]
